# Generated by Django 3.0.6 on 2020-05-20 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200520_1845'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
