# Generated by Django 3.0.6 on 2020-06-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200530_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='slug',
            field=models.TextField(default='this is new slug'),
        ),
    ]
