# Generated by Django 3.0.6 on 2020-06-27 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_signup_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='slug',
        ),
    ]
