# Generated by Django 3.0.6 on 2020-07-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20200705_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='user',
            field=models.CharField(choices=[('consumer', 'provider')], default='provider', max_length=240, null=True),
        ),
    ]
