# Generated by Django 3.0.6 on 2020-07-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20200718_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='user',
            field=models.CharField(choices=[('consumer', 'provider')], max_length=240, null=True),
        ),
    ]
