# Generated by Django 3.0.6 on 2020-07-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20200718_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='user',
            field=models.CharField(choices=[('consumer', 'CONSUMER'), ('provider', 'PROVIDER')], default='provider', max_length=240),
        ),
    ]
