# Generated by Django 3.0.6 on 2020-07-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20200719_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(max_length=140, unique=True),
        ),
    ]
